### ISSUE TITLE
Thanks ❤️ Found this project useful

### ISSUE THREAD

**Issue by salahturkmen** [mahmmd/moyasar_payment#1]
but returned value after payment is dynamic 
can change it to model

**Comment by mohammeddawida** [comment]
I will add it soon

**Comment by tanzeemhussain** [comment]
please send model soon or just tell us about response data

**Comment by salahturkmen** [comment]
ex:
id=79cced57-9deb-4c4b-8f48-59c124f79688
status=paid
message=Succeeded

**Comment by mohammeddawida** [comment]
@salahturkmen 
@tanzeemhussain 
I added a model, please test it
