### ISSUE TITLE
Wrong Number of paramters

### ISSUE THREAD

**Issue by AhmedAbogameel** [mahmmd/moyasar_payment#2]
I'm facing issue testing apple pay the message of the following code is "Wrong Number of paramters"
i can not understand what does that mean and what paramters it means?

```
PayModel res = await _moyasarPayment.applePay(
      amount: amount,
      publishableKey: _publishableKey,
      applepayMerchantId: _applePayMerchantID,
      paymentItems: {'Service Cost' : amount, 'Total Cost': amount},
      currencyCode: 'SAR',
      countryCode: 'SA',
      description: 'Paying for a service with apple pay.',
    );
```

**Comment by mohammeddawida** [comment]
Can you put the value of the sent amount?

**Comment by AhmedAbogameel** [comment]
1000.0

**Comment by AhmedAbogameel** [comment]
> Can you put the value of the sent amount?

1000.0

**Comment by mohammeddawida** [comment]
A positive integer in the smallest currency unit (e.g., 100 cents to charge an amount of $1.00, 100 halalah to charge an amount of 1 SAR, or 1 to charge an amount of ¥1, a 0-decimal currency) representing how much to charge the card. The minimum amount is $0.50 (or equivalent in charge currency).
