### ISSUE TITLE
apple pay return field validation

### ISSUE THREAD

**Issue by farhioussama1969** [mahmmd/moyasar_payment#3]
```
PayModel res = await MoyasarPayment().applePay(
        amount: 100.0,
        publishableKey: MoyasarPaymentGateway.publishableApiKey,
        applepayMerchantId: applepayMerchantId,
        paymentItems: items,
        currencyCode: 'SAR',
        countryCode: 'SA',
        description: 'description');
```
the function return field validation

**Comment by utrodus** [comment]
@farhioussama1969 are these moyasar_payment packages not working?

**Comment by farhioussama1969** [comment]
> @farhioussama1969 are these moyasar_payment packages not working?

Yeah some errors with the package in card payment
Use this fork version (i fixed all errors)
[https://github.com/farhioussama1969/moyasar_payment](https://github.com/farhioussama1969/moyasar_payment)

**Comment by mohammeddawida** [comment]
send amount number halalah not SAR
1 SAR = 100 halalah 
and amount is integer
