### ISSUE TITLE
Can't run project & run pod install / pod update after adding moyasar_payment package

### ISSUE THREAD

**Issue by utrodus** [mahmmd/moyasar_payment#7]
<details>
  <summary>When I execute the command pod install / pod update the error occurs, how to solve this:</summary>

![image](https://user-images.githubusercontent.com/24326642/194526676-d63957db-0043-48f4-af02-cf9d2c2d7e63.png)
</details>

<details>
  <summary>Output when try to run my project</summary>

Launching lib/main.dart on iPhone 11 in debug mode...

CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A moyasar_payment
      - Flutter
      - better_player
      - connectivity
      - device_info
      - firebase_core
      - firebase_dynamic_links
      - firebase_messaging
      - flutter_custom_tabs
      - flutter_local_notifications
      - flutter_native_timezone
      - flutter_statusbarcolor_ns
      - flutter_webview_plugin
      - geocoding
      - geolocator_apple
      - google_maps_flutter_ios
      - image_picker_ios
      - notification_permissions
      - onesignal_flutter
      - open_file
      - package_info
      - package_info_plus
      - path_provider_ios
      - pay_ios
      - permission_handler
      - sensors
      - share
      - share_plus
      - shared_preferences_ios
      - sqflite
      - uni_links
      - url_launcher_ios
      - vibration
      - wakelock
      - webview_flutter_wkwebview
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `better_player` from `.symlinks/plugins/better_player/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    firebase_core: Using Firebase SDK version '9.6.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_dynamic_links` from `.symlinks/plugins/firebase_dynamic_links/ios`
    firebase_dynamic_links: Using Firebase SDK version '9.6.0' defined in 'firebase_core'
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    firebase_messaging: Using Firebase SDK version '9.6.0' defined in 'firebase_core'
    -> Fetching podspec for `flutter_custom_tabs` from `.symlinks/plugins/flutter_custom_tabs/ios`
    -> Fetching podspec for `flutter_local_notifications` from `.symlinks/plugins/flutter_local_notifications/ios`
    -> Fetching podspec for `flutter_native_timezone` from `.symlinks/plugins/flutter_native_timezone/ios`
    -> Fetching podspec for `flutter_statusbarcolor_ns` from `.symlinks/plugins/flutter_statusbarcolor_ns/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `geocoding` from `.symlinks/plugins/geocoding/ios`
    -> Fetching podspec for `geolocator_apple` from `.symlinks/plugins/geolocator_apple/ios`
    -> Fetching podspec for `google_maps_flutter_ios` from `.symlinks/plugins/google_maps_flutter_ios/ios`
    -> Fetching podspec for `image_picker_ios` from `.symlinks/plugins/image_picker_ios/ios`
    -> Fetching podspec for `moyasar_payment` from `.symlinks/plugins/moyasar_payment/ios`
    -> Fetching podspec for `notification_permissions` from `.symlinks/plugins/notification_permissions/ios`
    -> Fetching podspec for `onesignal_flutter` from `.symlinks/plugins/onesignal_flutter/ios`
    -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `package_info_plus` from `.symlinks/plugins/package_info_plus/ios`
    -> Fetching podspec for `path_provider_ios` from `.symlinks/plugins/path_provider_ios/ios`
    -> Fetching podspec for `pay_ios` from `.symlinks/plugins/pay_ios/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `sensors` from `.symlinks/plugins/sensors/ios`
    -> Fetching podspec for `share` from `.symlinks/plugins/share/ios`
    -> Fetching podspec for `share_plus` from `.symlinks/plugins/share_plus/ios`
    -> Fetching podspec for `shared_preferences_ios` from `.symlinks/plugins/shared_preferences_ios/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `uni_links` from `.symlinks/plugins/uni_links/ios`
    -> Fetching podspec for `url_launcher_ios` from `.symlinks/plugins/url_launcher_ios/ios`
    -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter_wkwebview` from `.symlinks/plugins/webview_flutter_wkwebview/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_b_0.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/a/b/0/Cache/6.0.0/Cache.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_7_2_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/7/2/d/GCDWebServer/3.5.4/GCDWebServer.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_4_0_4.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/4/0/4/HLSCachingReverseProxyServer/0.1.0/HLSCachingReverseProxyServer.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_b_f_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/b/f/d/PINCache/3.0.3/PINCache.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/9.6.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/9.6.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/0/3/5/Firebase/9.6.0/Firebase.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_a_d_d.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/a/d/d/GoogleMaps/7.1.0/GoogleMaps.podspec.json exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "moyasar_payment":
      In Podfile:
        moyasar_payment (from `.symlinks/plugins/moyasar_payment/ios`)
    Specs satisfying the `moyasar_payment (from `.symlinks/plugins/moyasar_payment/ios`)` dependency were found, but they required a higher minimum deployment target.
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
    /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
    Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Error running pod install
Error launching application on iPhone 11.
Exited (sigterm)

</details>

**Flutter version: 2.10.2**
**Dart SDK version: 2.18.2**
**CocoaPods version: 1.11.3**

<details>
  <summary>Flutter Doctor :</summary>
  
utrodus@192 ~ % flutter doctor -v

[✓] Flutter (Channel stable, 2.10.2, on macOS 11.7 20G817 darwin-x64, locale en-ID)

**•** **Flutter version 2.10.2 at /Users/utrodus/fvm/versions/2.10.2**

**•** **Upstream repository https://github.com/flutter/flutter.git**

**•** **Framework revision 097d3313d8 (8 months ago), 2022-02-18 19:33:08 -0600**

**•** **Engine revision a83ed0e5e3**

**•** **Dart version 2.16.1**

**•** **DevTools version 2.9.2**

  

[✗] Android toolchain - develop for Android devices

**✗** **Unable to locate Android SDK.**

**Install Android Studio from: https://developer.android.com/studio/index.html**

**On first launch it will assist you in installing the Android SDK components.**

**(or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).**

**If the Android SDK has been installed to a custom location, please use**

**`flutter config --android-sdk` to update to that location.**

  

  

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)

**•** **Xcode at /Applications/Xcode.app/Contents/Developer**

**•** **CocoaPods version 1.11.3**

  

[✓] Chrome - develop for the web

**•** **Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome**

  

[!] Android Studio (not installed)

**•** **Android Studio not found; download from https://developer.android.com/studio/index.html**

**(or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).**

  

[✓] VS Code (version 1.72.0)

**•** **VS Code at /Applications/Visual Studio Code.app/Contents**

**•** **Flutter extension version 3.50.0**

  

[✓] Connected device (2 available)

**•** **iPhone 11 (mobile) • C87C7F59-CD9B-4D19-8306-19FA7D449199 • ios  •**

**com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)**

**•** **Chrome (web) • chrome • web-javascript • Google Chrome 106.0.5249.91**

  

[✓] HTTP Host Availability

**•** **All required HTTP hosts are available**

! Doctor found issues in 2 categories.
</details>

**Comment by aalrayes** [comment]
have you tried to set IOS version to 12.2 and above ?

**Comment by mohammeddawida** [comment]
![Screen Shot 2022-10-08 at 12 04 33 PM](https://user-images.githubusercontent.com/24524405/194700622-1029c398-8896-4734-a972-4a44b8e63925.png)

Change IOS Deployment Target to 12.2
